<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Home</h1>
    <form action="/" method="post">
        <input type="text" name="fullurl">
        <button type="submit">生成短域名</button>
    </form>
    
    <ul>
    <?
    foreach ($urls as $url)
        {
        echo '<li>' . $url['url_full'] . '</li>';
    }
    ?>
    </ul>
</body>
</html>