<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>简单的短域名服务</title>
    <link href="https://cdn.bootcss.com/bulma/0.7.1/css/bulma.min.css" rel="stylesheet">
    <link rel="icon" type="image/png" href="/favicon.png" />
</head>
<style>
body{
    font-family: "PingFang SC","Microsoft Yahei Light",sans-serif;
}
li b{
    font-family:monospace;
}
#url-input{
    width:500px;
}
input:-webkit-autofill,input:-webkit-autofill:hover,input:-webkit-autofill:focus {
  -webkit-box-shadow: 0 0 0px 1000px white inset;
  -webkit-text-fill-color: #333;
}
.form-section{
    margin-top:200px;
}
.url-footer{
    position:absolute;
    bottom:10px;
    left:50%;
}
@media screen and (max-width: 800px) { 
    .form-section{
        margin:200px 20px 0 20px;
    }
    #url-input{
        width: auto;
    }
 }
</style>
<body>
    <section class="hero is-primary is-bold">
    <div class="hero-body">
        <div class="container">
        <h1 class="title has-text-weight-light">
            简单的短域名服务
        </h1>
        </div>
    </div>
    </section>
    <div class="container">
        <div class="field has-addons has-addons-centered form-section">
            <div class="control">
                <input class="input is-medium" type="text" name="fullurl" id="url-input" spellcheck="false">
                <p class="help is-danger url-info" id="err-msg" style="display:none">请检查你输入的链接，如协议名是否正确</p>
            </div>
            <div class="control">
                <button class="button is-primary is-medium" id="submit-btn">生成</button>
            </div>
        </div>
    </div>
    <!-- <div class="url-footer">
        <iframe src="https://ghbtns.com/github-btn.html?user=abowloflrf&repo=url-shortener&type=star&count=true" frameborder="0" scrolling="0" width="170px" height="20px"></iframe>
    </div> -->
    <script src="https://cdn.bootcss.com/axios/0.18.0/axios.min.js"></script>
    <script src="https://cdn.bootcss.com/clipboard.js/2.0.1/clipboard.min.js"></script>
    <script src="js/app.js"></script>
</body>
</html>